In [1]:
import pandas as pd
df = pd.read_csv('customer_shopping_behavior.csv')
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,22,Male,Hoodie,Clothing,127.75,Miami,S,Blue,Winter,4.1,Yes,Standard,No,No,36,Cash,Quarterly
1,2,58,Male,Sneakers,Footwear,112.60,Houston,XL,Red,Spring,3.3,No,Free Shipping,No,No,9,Debit Card,Annually
2,3,52,Female,Coat,Outerwear,206.48,Seattle,XL,Red,Summer,4.6,Yes,Free Shipping,No,No,26,Credit Card,Bi-Weekly
3,4,40,Male,Boots,Footwear,96.90,Houston,S,Red,Spring,3.3,No,Free Shipping,No,No,2,Debit Card,Bi-Weekly
4,5,40,Male,Jewelry,Accessories,97.53,Houston,XL,Green,Winter,4.2,Yes,Standard,Yes,Yes,23,Debit Card,Annually

In [2]:
df.info()
# Looking at the info its clear that the platform is quite new as the number of active customers is <4000

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             12000 non-null  int64
 1   Age                     12000 non-null  int64
 2   Gender                  12000 non-null  object
 3   Item Purchased          12000 non-null  object
 4   Category                12000 non-null  object
 5   Purchase Amount (USD)   12000 non-null  float64
 6   Location                12000 non-null  object
 7   Size                    12000 non-null  object
 8   Color                   12000 non-null  object
 9   Season                  12000 non-null  object
 10  Review Rating           12000 non-null  float64
 11  Subscription Status     12000 non-null  object
 12  Shipping Type           12000 non-null  object
 13  Discount Applied        12000 non-null  object
 14  Promo Code Used         12000 non-null  object
 15  Previous Purchases      12000 non-null  int64
 16  Payment Method          12000 non-null  object
 17  Frequency of Purchases  12000 non-null  object
dtypes: float64(2), int64(3), object(13)
memory usage: 1.6+ MB

In [3]:
df.drop(columns=['Customer ID']).describe(include = 'all')

,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,12000.000000,12000,12000,12000,12000.000000,12000,12000,12000,12000,12000.000000,12000,12000,12000,12000,12000.000000,12000,12000
unique,NaN,2,21,4,NaN,5,4,5,4,NaN,2,3,2,2,NaN,4,5
top,NaN,Female,Jacket,Clothing,NaN,Miami,L,Black,Spring,NaN,No,Express,Yes,No,NaN,Cash,Monthly
freq,NaN,6315,1240,4629,NaN,2473,3046,2490,3079,NaN,7235,4032,6009,7849,NaN,3079,3061
mean,43.363500,NaN,NaN,NaN,99.269317,NaN,NaN,NaN,NaN,3.555508,NaN,NaN,NaN,NaN,14.439417,NaN,NaN
std,14.923134,NaN,NaN,NaN,41.646535,NaN,NaN,NaN,NaN,0.452438,NaN,NaN,NaN,NaN,8.676824,NaN,NaN
min,18.000000,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,1.800000,NaN,NaN,NaN,NaN,0.000000,NaN,NaN
25%,30.000000,NaN,NaN,NaN,68.557500,NaN,NaN,NaN,NaN,3.300000,NaN,NaN,NaN,NaN,8.000000,NaN,NaN
50%,43.000000,NaN,NaN,NaN,91.680000,NaN,NaN,NaN,NaN,3.600000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
75%,56.000000,NaN,NaN,NaN,125.555000,NaN,NaN,NaN,NaN,3.900000,NaN,NaN,NaN,NaN,19.000000,NaN,NaN
max,69.000000,NaN,NaN,NaN,253.710000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,60.000000,NaN,NaN

In [4]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             83
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [4]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount_(usd),location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases
0,1,22,Male,Hoodie,Clothing,127.75,Miami,S,Blue,Winter,4.1,Yes,Standard,No,No,36,Cash,Quarterly
1,2,58,Male,Sneakers,Footwear,112.60,Houston,XL,Red,Spring,3.3,No,Free Shipping,No,No,9,Debit Card,Annually
2,3,52,Female,Coat,Outerwear,206.48,Seattle,XL,Red,Summer,4.6,Yes,Free Shipping,No,No,26,Credit Card,Bi-Weekly
3,4,40,Male,Boots,Footwear,96.90,Houston,S,Red,Spring,3.3,No,Free Shipping,No,No,2,Debit Card,Bi-Weekly
4,5,40,Male,Jewelry,Accessories,97.53,Houston,XL,Green,Winter,4.2,Yes,Standard,Yes,Yes,23,Debit Card,Annually

In [5]:
df['review_rating'] = df.groupby('category')['review_rating'].transform(lambda x: x.fillna(x.median()))
# Median obviously is a better idea than average because of possible outliers
# Also its unrealistic(not professional) to compare ratings of one genre with other
df.isnull().sum()

customer_id               0
age                       0
gender                    0
item_purchased            0
category                  0
purchase_amount_(usd)     0
location                  0
size                      0
color                     0
season                    0
review_rating             0
subscription_status       0
shipping_type             0
discount_applied          0
promo_code_used           0
previous_purchases        0
payment_method            0
frequency_of_purchases    0
dtype: int64

In [6]:
# Introduce Age Groups
age_group = ['Young Adult', 'Adult', 'Middle Aged', 'Senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels = age_group)
df = df.rename(columns = {'purchase_amount_(usd)':'purchase_amt'})
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amt', 'location', 'size', 'color', 'season', 'review_rating',
       'subscription_status', 'shipping_type', 'discount_applied',
       'promo_code_used', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group'],
      dtype='object')

In [7]:
df['frequency_of_purchases'].unique()

array(['Quarterly', 'Annually', 'Bi-Weekly', 'Monthly', 'Weekly'],
      dtype=object)

In [8]:
# The customers working history is stored in string format - have to convert them to numbers
days = [14, 7, 365, 90, 14, 30, 90]
history = dict(zip(df['frequency_of_purchases'].unique(), days))
df['frequency_of_purchases'] = df['frequency_of_purchases'].map(history)
df = df.rename(columns = {'frequency_of_purchases' : 'purchase_frequency_days'})
df['purchase_frequency_days']

0         14
1          7
2        365
3        365
4          7
        ...
11995     14
11996    365
11997     90
11998     14
11999      7
Name: purchase_frequency_days, Length: 12000, dtype: int64

In [10]:
# We dont need 'discount_applied' and 'promo_code_used' as one implies other - proof:
(df['discount_applied'] == df['promo_code_used']).all()

np.False_

In [11]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amt', 'location', 'size', 'color', 'season', 'review_rating',
       'subscription_status', 'shipping_type', 'discount_applied',
       'promo_code_used', 'previous_purchases', 'payment_method',
       'purchase_frequency_days', 'age_group'],
      dtype='object')

In [11]:
pip install pandas sqlalchemy pymysql

Requirement already satisfied: pandas in C:\Users\sarth\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.2.3)
Requirement already satisfied: sqlalchemy in C:\Users\sarth\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.0.50)
Requirement already satisfied: pymysql in C:\Users\sarth\AppData\Local\Programs\Python\Python313\Lib\site-packages (1.2.0)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\sarth\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.2.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\sarth\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\sarth\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\sarth\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: greenlet>=1 in C:\Users\sarth\AppData\Local\Programs\Python\Python313\Lib\site-packages (from sqlalchemy) (3.5.1)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\sarth\AppData\Local\Programs\Python\Python313\Lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: six>=1.5 in C:\Users\sarth\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [12]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:root_password%40123@localhost/customers"
)

In [13]:
df.to_sql(
    name='customer_behavior',
    con=engine,
    if_exists='replace',  # or 'append'
    index=False
)

12000